# Generated by Django 4.1 on 2022-09-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_zip',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='zip_files/'),
        ),
    ]
