# Generated by Django 4.1 on 2022-09-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_upload_zip_zip_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='upload_zip',
            new_name='UploadZip',
        ),
    ]
