# Generated by Django 4.1 on 2022-10-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_uploadzip_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadzip',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
