# Generated by Django 4.1 on 2022-10-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_uploadzip_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadzip',
            name='user_id',
        ),
    ]
