# Generated by Django 4.1 on 2022-10-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bomres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BomRes',
            new_name='BomResult',
        ),
    ]
