# Generated by Django 4.1 on 2022-11-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_bomres_bomresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BomResult',
        ),
        migrations.AddField(
            model_name='uploadzip',
            name='zip_file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
