# Generated by Django 4.1 on 2022-11-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_uploadzip_zip_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadzip',
            old_name='zip_file',
            new_name='zip_file_path',
        ),
    ]
