# Generated by Django 4.1 on 2022-11-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_zip_file_uploadzip_zip_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadzip',
            name='zip_file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
