# Generated by Django 4.1 on 2022-08-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_useraccount_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_name',
            field=models.CharField(default='khan', max_length=255),
            preserve_default=False,
        ),
    ]
